### ISSUE TITLE
Entrego el pacial de objetos q es el recuperatorio

### ISSUE THREAD

**Issue by lchen2o4** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-Ro0xx0#1]
Emiliano Salvano y Luca Pavón @EmilianoSalvano @Lpavn
Juan Fernandes y Lucas Zheng @juanFdS @zhl27 
Juani Schuhmann y Dante Ortiz @jschuhmann47 @Effloresc3 
Tomás Antonio @T-J-Antonio
Gustavo Crespi y Manuel Torrente @gcrespi @manutorrente

**Comment by JuanFdS** [comment]
## Parte A
### Punto 1
❌ No se está retornando nada en la implementación de `aportaAl` de la clase `Varita`.
❌ Acorde a la consigna, las túnicas deberían aportar también su valor base.
⚠️ ¿Por qué está el método `poderInato` del `Mago` si luego él mismo no lo usa? En este caso podemos o bien asumir que se cargará un valor correcto o hacerlo constante y hacer una validación similar a la del punto B.1.
⚠️ El método `aportaAl` no tiene un nombre muy claro.
⚠️ El enunciado no indica que la túnica épica sea "un subtipo de túnica común", si en el futuro cambiase el comportamiento de las túncias comunes o de las épicas podría romperse esta herencia.
Fuera de eso, está bien ✅
## Parte B
❌ En esta implementación, al modelarlo usando herencia, el mago siempre va a ser de la misma categoría, lo cual no es correcto según el enunciado:
> Estas características dependen de la categoría que el mago tenga actualmente, la cual puede cambiar a lo largo del tiempo.
⚠️ Los operadores de "suma y asignación" y "resta y asignación" son `+=` y `-=`.
## Parte B
### Punto 1
❌ La condición en `initialize` debería ser la inversa. Además, el error podría tener un nombre más expresivo.
### Punto 2
❌ Incompleto.
### Punto 3
❌ Incompleto.
## Tests
N/A.

Nota: 4
